platform :ios, '13.0'

def install_common
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxAppState', '~> 1.6'
  pod 'RxDataSources'
  pod 'RxGesture'
  pod 'WeakMapTable'
  pod 'SwiftLint'
  pod 'Then', '~> 2.7'
  pod 'Introspect'
end

target 'opgg' do
  use_frameworks!
  install_common
  pod 'SnapKit', '~> 5.6.0'
  pod 'Alamofire'
  pod 'Kingfisher', '~> 5.0'
end
